printWidth: 140
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: consistent
jsxSingleQuote: false
bracketSpacing: true
arrowParens: always
plugins:
  - prettier-plugin-svelte
overrides:
  - files: .vscode/*.json
    options:
      tabWidth: 4
  - files: '*.svelte'
    options:
      parser: svelte
